# Generated by Django 2.1.5 on 2019-01-25 02:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usertype',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='组成员'),
        ),
        migrations.AddField(
            model_name='step',
            name='action',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='flow.Action', verbose_name='处理方式'),
        ),
        migrations.AddField(
            model_name='step',
            name='flow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flow.Flow', verbose_name='流程'),
        ),
        migrations.AddField(
            model_name='step',
            name='from_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='from_Step', to='flow.Status', verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='step',
            name='to_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='to_Step', to='flow.Status', verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='status',
            name='actions',
            field=models.ManyToManyField(blank=True, help_text='流程所处状态具有的处理方式:1:确认;2:回退;3:撤回;4:否决;', to='flow.Action', verbose_name='处理方式'),
        ),
        migrations.AddField(
            model_name='status',
            name='flow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flow.Flow', verbose_name='流程'),
        ),
        migrations.AddField(
            model_name='status',
            name='user_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='flow.UserType', verbose_name='用户组'),
        ),
        migrations.AddField(
            model_name='flow',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
    ]
