# Generated by Django 2.1.5 on 2019-01-28 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0004_auto_20190128_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='pre_user_type',
        ),
    ]
