# Generated by Django 2.1.5 on 2019-01-29 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0005_remove_status_pre_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='pre_user_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pre_status_user_type', to='flow.UserType', verbose_name='回退组'),
        ),
    ]
