# Generated by Django 2.1.5 on 2019-01-18 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, height_field=50, null=True, upload_to='', verbose_name='照片', width_field=50),
        ),
    ]
