# Generated by Django 2.1.5 on 2019-01-25 07:45

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flow', '0003_auto_20190125_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_title', models.CharField(max_length=100, verbose_name='标题')),
                ('order_content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='内容')),
                ('status', models.CharField(blank=True, choices=[('开始', '开始'), ('进行中', '进行中'), ('结束', '结束')], max_length=100, null=True, verbose_name='工单状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='工单创建时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='工单结束时间')),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flow.Flow', verbose_name='流程')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_create_uesr', to=settings.AUTH_USER_MODEL, verbose_name='发起人')),
            ],
            options={
                'verbose_name': '工单',
                'verbose_name_plural': '工单',
                'ordering': ['flow__id'],
            },
        ),
        migrations.CreateModel(
            name='OrderStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('action', models.ForeignKey(blank=True, help_text='流程所处状态具有的处理方式:1:完成;2:回退;3:确认;4:否决;', null=True, on_delete=django.db.models.deletion.PROTECT, to='flow.Action', verbose_name='处理方式')),
                ('action_uesr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='action_uesr', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('end_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='end_status', to='flow.Status', verbose_name='结束状态')),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flow.Flow', verbose_name='流程')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.Order', verbose_name='工单')),
                ('pre_action_uesr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pre_action_uesr', to=settings.AUTH_USER_MODEL, verbose_name='上一操作人')),
                ('start_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='start_status', to='flow.Status', verbose_name='开始状态')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='flow.Step', verbose_name='步骤')),
            ],
            options={
                'verbose_name': '工单详细步骤',
                'verbose_name_plural': '工单详细步骤',
                'ordering': ['id'],
            },
        ),
    ]
