# Generated by Django 2.1.5 on 2019-01-28 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0005_remove_status_pre_user_type'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(verbose_name='状态')),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flow.Flow', verbose_name='流程')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.Order', verbose_name='工单')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flow.Status', verbose_name='节点')),
            ],
            options={
                'verbose_name': '工单实例',
                'verbose_name_plural': '工单实例',
                'ordering': ['order__id', 'status__id'],
            },
        ),
    ]
