# Generated by Django 2.1.5 on 2019-01-29 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0006_status_pre_user_type'),
        ('order', '0004_auto_20190128_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinstance',
            name='pre_user_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pre_order_user_type', to='flow.UserType', verbose_name='回退组'),
        ),
        migrations.AddField(
            model_name='orderinstance',
            name='user_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_user_type', to='flow.UserType', verbose_name='用户组'),
        ),
    ]
