# Generated by Django 2.1.5 on 2019-01-29 01:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0005_auto_20190129_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderinstance',
            name='pre_user_type',
        ),
        migrations.RemoveField(
            model_name='orderinstance',
            name='user_type',
        ),
        migrations.AddField(
            model_name='orderinstance',
            name='action_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_user_type', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='orderinstance',
            name='pre_action_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pre_order_user_type', to=settings.AUTH_USER_MODEL, verbose_name='回退'),
        ),
    ]
