# Generated by Django 2.1.5 on 2019-01-29 01:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20190129_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinstance',
            name='action_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='action_user', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='orderinstance',
            name='pre_action_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pre_action_user', to=settings.AUTH_USER_MODEL, verbose_name='回退'),
        ),
    ]
