# Generated by Django 2.1.5 on 2019-01-29 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20190129_0938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderstep',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='orderstep',
            name='pre_action_uesr',
        ),
        migrations.RemoveField(
            model_name='orderstep',
            name='start_time',
        ),
        migrations.AddField(
            model_name='orderstep',
            name='action_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='时间'),
        ),
    ]
