# Generated by Django 2.1.5 on 2019-01-29 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20190129_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderstep',
            name='step',
        ),
        migrations.AlterField(
            model_name='orderstep',
            name='action_uesr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='action_uesr', to=settings.AUTH_USER_MODEL, verbose_name='操作人'),
        ),
    ]
