# Generated by Django 2.1.5 on 2019-02-13 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20190129_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZhouBao',
            fields=[
            ],
            options={
                'verbose_name': '周报',
                'verbose_name_plural': '周报',
                'proxy': True,
                'indexes': [],
            },
            bases=('order.orderstep',),
        ),
        migrations.AlterModelOptions(
            name='orderinstance',
            options={'ordering': ['order__id', 'status__id'], 'verbose_name': '待办', 'verbose_name_plural': '待办'},
        ),
        migrations.AlterModelOptions(
            name='orderstep',
            options={'ordering': ['id'], 'verbose_name': '详情', 'verbose_name_plural': '详情'},
        ),
        migrations.AlterField(
            model_name='orderinstance',
            name='action_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='action_user', to=settings.AUTH_USER_MODEL, verbose_name='当前操作用户'),
        ),
        migrations.AlterField(
            model_name='orderinstance',
            name='pre_action_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pre_action_user', to=settings.AUTH_USER_MODEL, verbose_name='当前回退用户'),
        ),
    ]
